import {
  createAsyncThunk,
  createSelector,
  createSlice,
  PayloadAction,
} from "@reduxjs/toolkit";
import { UserDto } from "@skill-test/data/dto/UserDto";
import dataStore from "../../utils/dataStore";
import {
  createUser as apiCreateUser,
  getCurrentUser,
  login,
  logout,
} from "../../api/openApi";
import { CoreState } from "../store";
import { LoadingState } from "../LoadingState";

export enum LoginDialogMode {
  logIn = "Log In",
  signUp = "Sign Up",
}
export interface UsersState {
  user?: UserDto;
  userLoading: LoadingState;
  userLodingError?: string;

  userLoginError?: string;
  userCreateError?: string;

  loginDialogMode?: LoginDialogMode;
}

const initialState: UsersState = {
  user: dataStore.getUser(),
  userLoading: LoadingState.IDLE,
};

// https://www.newline.co/@bespoyasov/how-to-use-thunks-with-redux-toolkit-and-typescript--1e65fc64
export const loadCurrentUser = createAsyncThunk<UserDto>(
  "users/loadCurrentUser",
  async (_, thunkAPI) => {
    try {
      const user = await getCurrentUser();
      dataStore.setUser(user);
      return user;
    } catch (error) {
      return thunkAPI.rejectWithValue(error.message);
    }
  }
);

export interface LoginUser {
  username: string;
  password: string;
}

export const loginUser = createAsyncThunk<UserDto, LoginUser>(
  "users/loginUser",
  async (loginUser, thunkAPI) => {
    try {
      const user = await login(loginUser.username, loginUser.password);
      dataStore.setUser(user);
      return user;
    } catch (error) {
      return thunkAPI.rejectWithValue(error.message);
    }
  }
);

export const createUser = createAsyncThunk<UserDto, LoginUser>(
  "users/createUser",
  async (loginUser, thunkAPI) => {
    try {
      const user = await apiCreateUser(loginUser.username, loginUser.password);
      dataStore.setUser(user);
      return user;
    } catch (error) {
      return thunkAPI.rejectWithValue(error.message);
    }
  }
);

export const logoutUser = createAsyncThunk<Response | void>(
  "users/logoutUser",
  async (loginUser) => {
    await logout();
    dataStore.logOut();
    document.location.href = "/";
  }
);

export const usersSlice = createSlice({
  name: "users",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    showLogin(state) {
      state.loginDialogMode = LoginDialogMode.logIn;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.userCreateError = undefined;
    },
    showSignup(state) {
      state.loginDialogMode = LoginDialogMode.signUp;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.userCreateError = undefined;
    },
    closeLoginDialog(state) {
      state.loginDialogMode = undefined;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.userCreateError = undefined;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    // login
    [loginUser.pending as any]: (state: UsersState) => {
      state.user = undefined;
      state.userLoading = LoadingState.LOADING;
    },
    [loginUser.fulfilled as any]: (
      state: UsersState,
      action: PayloadAction<UserDto>
    ) => {
      state.user = action.payload;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.loginDialogMode = undefined;
      state.userLoading = LoadingState.LOADED;
    },
    [loginUser.rejected as any]: (
      state: UsersState,
      action: PayloadAction<string>
    ) => {
      state.userLoginError = action.payload;
      state.userLoading = LoadingState.ERROR;
    },

    // load current user
    [loadCurrentUser.pending as any]: (state: UsersState) => {
      state.user = undefined;
      state.userLoading = LoadingState.LOADING;
    },
    [loadCurrentUser.fulfilled as any]: (
      state: UsersState,
      action: PayloadAction<UserDto>
    ) => {
      state.user = action.payload;
      state.userLoading = LoadingState.LOADED;
    },
    [loadCurrentUser.rejected as any]: (
      state: UsersState,
      action: PayloadAction<string>
    ) => {
      state.userLodingError = action.payload;
      state.userLoading = LoadingState.ERROR;
      console.log(state, action);
    },

    // signup, create user
    [createUser.pending as any]: (state: UsersState) => {
      state.user = undefined;
      state.userCreateError = undefined;
      state.userLoading = LoadingState.LOADING;
    },
    [createUser.fulfilled as any]: (
      state: UsersState,
      action: PayloadAction<UserDto>
    ) => {
      state.user = undefined;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.loginDialogMode = undefined;
      state.userCreateError = undefined;
      state.userLoading = LoadingState.LOADED;
    },
    [createUser.rejected as any]: (
      state: UsersState,
      action: PayloadAction<string>
    ) => {
      state.userCreateError = action.payload;
      state.userLoading = LoadingState.ERROR;
    },
  },
});

export const { showLogin, showSignup, closeLoginDialog } = usersSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUser = createSelector(
  (state: CoreState) => ({
    user: state.users.user,
    userLoading: state.users.userLoading,
    userLoginError: state.users.userLoginError,
    userLodingError: state.users.userLodingError,
    userCreateError: state.users.userCreateError,
    loginDialogMode: state.users.loginDialogMode,
  }),
  (state) => state
);

export default usersSlice.reducer;
