import {
  createAsyncThunk,
  createSelector,
  createSlice,
  PayloadAction,
} from "@reduxjs/toolkit";
import { UserDto } from "@skill-test/data/dto/UserDto";
import dataStore from "../../api/dataStore";
import {
  createUser as apiCreateUser,
  getCurrentUser,
  login,
  logout,
} from "../../api/openApi";
import { CoreState } from "../../store";
import { LoadingState } from "../LoadingState";

export interface UsersState {
  user?: UserDto;
  userLoading: LoadingState;
  userLoginError?: string;
  userLodingError?: string;
}

const initialState: UsersState = {
  user: dataStore.getUser(),
  userLoading: LoadingState.IDLE,
};

// https://www.newline.co/@bespoyasov/how-to-use-thunks-with-redux-toolkit-and-typescript--1e65fc64
export const loadCurrentUser = createAsyncThunk<UserDto>(
  "users/loadCurrentUser",
  async () => {
    const user = await getCurrentUser();
    dataStore.setUser(user);
    return user;
  }
);

export interface LoginUser {
  username: string;
  password: string;
}

export const loginUser = createAsyncThunk<UserDto, LoginUser>(
  "users/loginUser",
  async (loginUser, thunkAPI) => {
    try {
      const user = await login(loginUser.username, loginUser.password);
      dataStore.setUser(user);
      return user;
    } catch (error) {
      return thunkAPI.rejectWithValue(error.message);
    }
  }
);

export const createUser = createAsyncThunk<UserDto, LoginUser>(
  "users/createUser",
  async (loginUser) =>
    await apiCreateUser(loginUser.username, loginUser.password)
);

export const logoutUser = createAsyncThunk<Response | void>(
  "users/logoutUser",
  async (loginUser) => {
    await logout();
    dataStore.logOut();
  }
);

export const usersSlice = createSlice({
  name: "users",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    // login
    [loginUser.pending as any]: (state: UsersState) => {
      state.user = undefined;
      state.userLoading = LoadingState.LOADING;
    },
    [loginUser.fulfilled as any]: (
      state: UsersState,
      action: PayloadAction<UserDto>
    ) => {
      state.user = action.payload;
      state.userLodingError = undefined;
      state.userLoginError = undefined;
      state.userLoading = LoadingState.LOADED;
    },
    [loginUser.rejected as any]: (
      state: UsersState,
      action: PayloadAction<string>
    ) => {
      state.userLoginError = action.payload;
      state.userLoading = LoadingState.ERROR;
    },

    // ----------------------
    [loadCurrentUser.pending as any]: (state: UsersState) => {
      state.user = undefined;
      state.userLoading = LoadingState.LOADING;
    },
    [loadCurrentUser.fulfilled as any]: (
      state: UsersState,
      action: PayloadAction<UserDto>
    ) => {
      state.user = action.payload;
      state.userLoading = LoadingState.LOADED;
    },
    [loadCurrentUser.rejected as any]: (
      state: UsersState,
      action: PayloadAction<any>
    ) => {
      state.userLodingError = action.error.message;
      state.userLoading = LoadingState.ERROR;
      console.log(state, action);
    },
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUser = createSelector(
  (state: CoreState) => ({
    user: state.users.user,
    userLoading: state.users.userLoading,
    userLoginError: state.users.userLoginError,
    userLodingError: state.users.userLodingError,
  }),
  (state) => state
);

export default usersSlice.reducer;
