import {
  createAsyncThunk,
  createSelector,
  createSlice,
  PayloadAction,
} from "@reduxjs/toolkit";
import { Language } from "../../types/Language";
import { getCookie, setCookie } from "../../utils/cookies";
import { timeout } from "../../utils/utils";
import { CoreState } from "../store";

export interface LangsState {
  locale: Language;
  defaultLang: Language;
  selectedLang: Language;
}

const NEXT_LOCALE = "NEXT_LOCALE";

const initialState: LangsState = {
  locale: (getCookie(NEXT_LOCALE) as Language) || Language.en,
  defaultLang: Language.en,
  selectedLang: Language.en,
};

// https://www.newline.co/@bespoyasov/how-to-use-thunks-with-redux-toolkit-and-typescript--1e65fc64
export const setLocale = createAsyncThunk<Language, Language>(
  "langs/setLocale",
  async (value) => {
    await timeout(() => {
      setCookie({ name: NEXT_LOCALE, value, path: "/" });
    }, 100);

    return value;
  }
);

export const langsSlice = createSlice({
  name: "langs",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setDefaultLang: (state, { payload }: PayloadAction<Language>) => {
      state.defaultLang = payload;
    },
    selectLang: (state, { payload }: PayloadAction<Language>) => {
      state.selectedLang = payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [setLocale.fulfilled as any]: (
      state: LangsState,
      { payload }: PayloadAction<Language>
    ) => {
      if (state.locale !== payload) document.location.reload();
    },
  },
});

export const { setDefaultLang, selectLang } = langsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectLangs = createSelector(
  (state: CoreState) => ({
    locale: state.langs.locale,
    defaultLang: state.langs.defaultLang,
    selectedLang: state.langs.selectedLang,
  }),
  (state) => state
);

export default langsSlice.reducer;
